DELETE FROM job_post
WHERE job_id IN (
    'JOB1001', 'JOB1002', 'JOB1003', 'JOB1004', 'JOB1005',
    'JOB1006', 'JOB1007', 'JOB1008', 'JOB1009', 'JOB1010',
    'JOB1011', 'JOB1012'
);

DELETE FROM company
WHERE company_id IN (
    'COM1001', 'COM1002', 'COM1003', 'COM1004',
    'COM1005', 'COM1006'
);

INSERT INTO company (
    company_id,
    company_name,
    company_logo,
    industry_name,
    company_stage,
    company_size,
    company_intro,
    create_time,
    update_time,
    del_flag
) VALUES
(
    'COM1001',
    '星帆科技',
    'https://demo.example.com/logo/xingfan.png',
    '互联网',
    'B轮',
    '100-499人',
    '专注企业招聘和人才服务平台建设。',
    NOW(),
    NOW(),
    0
),
(
    'COM1002',
    '木舟云',
    'https://demo.example.com/logo/muzhou.png',
    '云计算',
    'C轮',
    '500-999人',
    '提供云原生平台和中间件解决方案。',
    NOW(),
    NOW(),
    0
),
(
    'COM1003',
    '极川网络',
    'https://demo.example.com/logo/jichuan.png',
    '企业服务',
    'A轮',
    '50-99人',
    '聚焦 B 端协同办公和数据中台产品。',
    NOW(),
    NOW(),
    0
),
(
    'COM1004',
    '海岚数据',
    'https://demo.example.com/logo/hailan.png',
    '大数据',
    '已上市',
    '1000-9999人',
    '提供实时数仓、指标平台和智能分析服务。',
    NOW(),
    NOW(),
    0
),
(
    'COM1005',
    '曜石软件',
    'https://demo.example.com/logo/yaoshi.png',
    '金融科技',
    '成熟期',
    '500-999人',
    '面向金融机构提供风控与交易系统。',
    NOW(),
    NOW(),
    0
),
(
    'COM1006',
    '澄明科技',
    'https://demo.example.com/logo/chengming.png',
    '互联网',
    '天使轮',
    '20-99人',
    '团队以 Java 后端和 AI 应用开发为主。',
    NOW(),
    NOW(),
    0
);

INSERT INTO job_post (
    job_id,
    company_id,
    title,
    job_summary,
    job_description,
    role_category,
    role_tags,
    skill_tags,
    industry_tags,
    benefit_tags,
    highlight_tags,
    location,
    city,
    district,
    work_mode,
    employment_type,
    education_requirement,
    preferred_major,
    experience_level,
    min_experience_years,
    max_experience_years,
    internship_months,
    salary_min_monthly,
    salary_max_monthly,
    salary_months,
    applicant_count,
    apply_url,
    posted_at,
    status,
    country,
    create_time,
    update_time,
    del_flag
) VALUES
(
    'JOB1001',
    'COM1001',
    'Java 后端开发工程师',
    '负责 Spring Boot 微服务、MySQL、Redis 开发，参与招聘平台核心链路建设。',
    '负责职位推荐、画像标签匹配和核心交易链路服务开发，参与服务治理与性能优化。',
    '后端开发',
    '["Java后端","招聘平台","微服务"]',
    '["Java","Spring Boot","MySQL","Redis"]',
    '["互联网","招聘"]',
    '["双休","年度体检"]',
    '["核心系统","画像匹配","高成长"]',
    '上海',
    '上海',
    '徐汇区',
    '混合办公',
    '全职',
    '本科及以上',
    '计算机相关专业',
    'JUNIOR',
    1,
    3,
    NULL,
    25,
    40,
    15,
    18,
    'https://demo.example.com/jobs/JOB1001',
    DATE_SUB(NOW(), INTERVAL 2 HOUR),
    'ONLINE',
    '中国大陆',
    NOW(),
    NOW(),
    0
),
(
    'JOB1002',
    'COM1001',
    '校招 Java 工程师',
    '参与职位搜索、推荐排序和用户画像系统开发，要求熟悉 Java 与 SQL。',
    '面向校招生，参与画像服务、推荐接口和后台业务的迭代开发。',
    '平台研发',
    '["校招","Java","推荐系统"]',
    '["Java","SQL","Spring Boot"]',
    '["互联网","云计算"]',
    '["校招培养","导师制"]',
    '["校招友好","成长快"]',
    '上海',
    '上海',
    '浦东新区',
    '现场办公',
    '校招',
    '本科',
    '计算机相关专业',
    'NEW_GRAD',
    0,
    1,
    NULL,
    18,
    26,
    14,
    31,
    'https://demo.example.com/jobs/JOB1002',
    DATE_SUB(NOW(), INTERVAL 6 HOUR),
    'ONLINE',
    '中国大陆',
    NOW(),
    NOW(),
    0
),
(
    'JOB1003',
    'COM1002',
    '高级 Java 平台工程师',
    '负责分布式调度、消息队列、链路追踪和高并发服务治理。',
    '负责平台级中间件建设，强调分布式、服务治理和调度编排能力。',
    '平台研发',
    '["Java","平台研发","调度系统"]',
    '["Java","MQ","分布式","链路追踪"]',
    '["云计算","中间件"]',
    '["餐补","弹性办公"]',
    '["高并发","平台化"]',
    '杭州',
    '杭州',
    '西湖区',
    '混合办公',
    '全职',
    '本科及以上',
    '计算机相关专业',
    '3-5年',
    3,
    5,
    NULL,
    35,
    50,
    16,
    22,
    'https://demo.example.com/jobs/JOB1003',
    DATE_SUB(NOW(), INTERVAL 10 HOUR),
    'ONLINE',
    '中国大陆',
    NOW(),
    NOW(),
    0
),
(
    'JOB1004',
    'COM1002',
    'Java 架构师',
    '主导云原生中台架构设计，要求熟悉 Spring Cloud、Redis、Kafka。',
    '承担中台架构设计、技术选型和关键系统拆分，适合资深平台候选人。',
    '架构设计',
    '["架构师","云原生","平台"]',
    '["Spring Cloud","Redis","Kafka","Java"]',
    '["云计算","企业服务"]',
    '["长期激励","年度奖金"]',
    '["架构主导","技术影响力"]',
    '杭州',
    '杭州',
    '余杭区',
    '混合办公',
    '全职',
    '本科及以上',
    '计算机相关专业',
    '5-10年',
    5,
    10,
    NULL,
    45,
    65,
    16,
    12,
    'https://demo.example.com/jobs/JOB1004',
    DATE_SUB(NOW(), INTERVAL 1 DAY),
    'ONLINE',
    '中国大陆',
    NOW(),
    NOW(),
    0
),
(
    'JOB1005',
    'COM1003',
    'Java 开发实习生',
    '参与后台接口开发和测试，熟悉 Java、Spring Boot、MySQL 优先。',
    '适合在校生，参与基础接口、测试和数据处理任务，强调成长性。',
    '后端开发',
    '["实习","后端开发"]',
    '["Java","Spring Boot","MySQL"]',
    '["企业服务"]',
    '["导师带教","免费午餐"]',
    '["实习转正","学习机会多"]',
    '广州',
    '广州',
    '天河区',
    '现场办公',
    '实习',
    '本科及以上',
    '计算机相关专业',
    'STUDENT',
    0,
    0,
    3,
    4,
    6,
    NULL,
    45,
    'https://demo.example.com/jobs/JOB1005',
    DATE_SUB(NOW(), INTERVAL 3 HOUR),
    'ONLINE',
    '中国大陆',
    NOW(),
    NOW(),
    0
),
(
    'JOB1006',
    'COM1003',
    '后端开发工程师',
    '负责企业服务平台接口设计、缓存优化和权限系统建设。',
    '承担权限中心、缓存层和后台 API 研发工作，偏业务中台方向。',
    '后端开发',
    '["后端开发","企业服务"]',
    '["Java","Redis","权限系统"]',
    '["企业服务"]',
    '["双休","绩效奖金"]',
    '["业务中台","成长空间"]',
    '深圳',
    '深圳',
    '南山区',
    '混合办公',
    '全职',
    '本科',
    '计算机相关专业',
    '1-3年',
    1,
    3,
    NULL,
    20,
    30,
    14,
    16,
    'https://demo.example.com/jobs/JOB1006',
    DATE_SUB(NOW(), INTERVAL 9 HOUR),
    'ONLINE',
    '中国大陆',
    NOW(),
    NOW(),
    0
),
(
    'JOB1007',
    'COM1004',
    '大数据平台 Java 工程师',
    '负责实时数仓平台后端开发，要求熟悉 Java、Flink、MySQL、Redis。',
    '面向实时数仓与分析平台建设，强调数据链路和平台服务能力。',
    '数据平台',
    '["大数据","平台研发"]',
    '["Java","Flink","MySQL","Redis"]',
    '["大数据","数据平台"]',
    '["年度体检","补充商业险"]',
    '["平台型业务","数据方向"]',
    '北京',
    '北京',
    '朝阳区',
    '混合办公',
    '全职',
    '本科及以上',
    '计算机/数据相关专业',
    '3-5年',
    3,
    5,
    NULL,
    28,
    42,
    16,
    27,
    'https://demo.example.com/jobs/JOB1007',
    DATE_SUB(NOW(), INTERVAL 20 HOUR),
    'ONLINE',
    '中国大陆',
    NOW(),
    NOW(),
    0
),
(
    'JOB1008',
    'COM1004',
    '推荐算法平台后端工程师',
    '负责用户画像、召回排序、特征服务和推荐链路平台化。',
    '负责画像、召回、特征服务和推荐平台后端，适合做画像推荐联调。',
    '推荐平台',
    '["推荐系统","画像平台"]',
    '["Java","Redis","推荐系统","画像"]',
    '["大数据","AI应用"]',
    '["弹性办公","技术分享"]',
    '["画像联动","推荐链路"]',
    '上海',
    '上海',
    '杨浦区',
    '混合办公',
    '全职',
    '本科及以上',
    '计算机/算法相关专业',
    '3-5年',
    3,
    5,
    NULL,
    32,
    48,
    16,
    14,
    'https://demo.example.com/jobs/JOB1008',
    DATE_SUB(NOW(), INTERVAL 30 HOUR),
    'ONLINE',
    '中国大陆',
    NOW(),
    NOW(),
    0
),
(
    'JOB1009',
    'COM1005',
    'Java 后端开发工程师(金融方向)',
    '参与交易系统、风控平台和账务服务开发，要求扎实 SQL 能力。',
    '聚焦交易、风控与账务系统，适合希望进入金融科技方向的后端同学。',
    '后端开发',
    '["Java后端","金融系统"]',
    '["Java","SQL","风控"]',
    '["金融科技"]',
    '["年度奖金","下午茶"]',
    '["金融核心系统","稳定业务"]',
    '上海',
    '上海',
    '黄浦区',
    '现场办公',
    '全职',
    '本科及以上',
    '计算机/金融科技相关专业',
    '3-5年',
    3,
    5,
    NULL,
    30,
    45,
    14,
    19,
    'https://demo.example.com/jobs/JOB1009',
    DATE_SUB(NOW(), INTERVAL 5 HOUR),
    'ONLINE',
    '中国大陆',
    NOW(),
    NOW(),
    0
),
(
    'JOB1010',
    'COM1005',
    '中级 Java 工程师',
    '负责支付系统和清结算服务开发，熟悉 Spring Boot、MySQL、MQ。',
    '负责支付链路和清结算服务研发，关注稳定性和高可用。',
    '支付平台',
    '["支付系统","Java"]',
    '["Spring Boot","MySQL","MQ"]',
    '["金融科技","支付"]',
    '["双休","年终奖"]',
    '["核心支付","稳定高并发"]',
    '深圳',
    '深圳',
    '福田区',
    '混合办公',
    '全职',
    '本科',
    '计算机相关专业',
    'JUNIOR',
    2,
    4,
    NULL,
    22,
    32,
    14,
    11,
    'https://demo.example.com/jobs/JOB1010',
    DATE_SUB(NOW(), INTERVAL 2 DAY),
    'ONLINE',
    '中国大陆',
    NOW(),
    NOW(),
    0
),
(
    'JOB1011',
    'COM1006',
    'Java 后端开发实习生',
    '参与简历画像、职位推荐和后台管理系统开发，要求 Java 基础扎实。',
    '适合希望做画像服务和推荐系统后台的在校生，场景与当前项目贴近。',
    '画像推荐',
    '["实习","画像服务","推荐系统"]',
    '["Java","Spring Boot","MySQL","画像"]',
    '["互联网","AI应用"]',
    '["导师带教","转正机会"]',
    '["画像联调","推荐业务"]',
    '上海',
    '上海',
    '闵行区',
    '现场办公',
    '实习',
    '本科及以上',
    '计算机相关专业',
    'STUDENT',
    0,
    0,
    4,
    5,
    7,
    NULL,
    52,
    'https://demo.example.com/jobs/JOB1011',
    DATE_SUB(NOW(), INTERVAL 1 HOUR),
    'ONLINE',
    '中国大陆',
    NOW(),
    NOW(),
    0
),
(
    'JOB1012',
    'COM1006',
    '初级后端开发工程师',
    '负责 Spring Boot、Redis、MySQL 接口开发和服务维护。',
    '负责接口服务和稳定性维护，适合 1-3 年经验的 Java 后端工程师。',
    '后端开发',
    '["Java后端","服务维护"]',
    '["Spring Boot","Redis","MySQL"]',
    '["互联网"]',
    '["远程办公","节日福利"]',
    '["远程友好","成长稳定"]',
    '苏州',
    '苏州',
    '工业园区',
    '远程办公',
    '全职',
    '本科',
    '计算机相关专业',
    'JUNIOR',
    1,
    3,
    NULL,
    18,
    25,
    13,
    9,
    'https://demo.example.com/jobs/JOB1012',
    DATE_SUB(NOW(), INTERVAL 4 DAY),
    'ONLINE',
    '中国大陆',
    NOW(),
    NOW(),
    0
);
