CREATE TABLE IF NOT EXISTS `llm_call_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `trace_id` varchar(64) NOT NULL COMMENT '一次业务大模型调用链路ID',
  `call_id` varchar(64) NOT NULL COMMENT '单次模型尝试ID/MQ消息Key',
  `scene` varchar(64) DEFAULT NULL COMMENT '业务场景',
  `biz_id` varchar(128) DEFAULT NULL COMMENT '业务ID',
  `user_id` bigint DEFAULT NULL COMMENT '用户ID',
  `provider` varchar(32) NOT NULL COMMENT '模型供应商',
  `model_id` varchar(64) NOT NULL COMMENT '配置中的模型ID',
  `model_name` varchar(128) DEFAULT NULL COMMENT '真实模型名',
  `endpoint` varchar(255) DEFAULT NULL COMMENT '请求端点',
  `thinking` tinyint(1) DEFAULT 0 COMMENT '是否启用思考模式',
  `response_format` varchar(64) DEFAULT NULL COMMENT '响应格式',
  `temperature` decimal(4,2) DEFAULT NULL COMMENT 'temperature',
  `max_tokens` int DEFAULT NULL COMMENT 'max_tokens',
  `status` varchar(16) NOT NULL COMMENT 'SUCCESS、FAILED',
  `duration_ms` bigint NOT NULL COMMENT '调用耗时毫秒',
  `http_status` int DEFAULT NULL COMMENT 'HTTP状态码',
  `error_type` varchar(64) DEFAULT NULL COMMENT '错误类型',
  `error_code` varchar(128) DEFAULT NULL COMMENT '错误码',
  `error_message` varchar(1024) DEFAULT NULL COMMENT '错误摘要',
  `prompt_chars` int DEFAULT NULL COMMENT '请求消息字符数',
  `response_chars` int DEFAULT NULL COMMENT '响应字符数',
  `prompt_hash` varchar(64) DEFAULT NULL COMMENT '请求内容SHA-256',
  `response_hash` varchar(64) DEFAULT NULL COMMENT '响应内容SHA-256',
  `input_tokens` int DEFAULT NULL COMMENT '输入token数',
  `output_tokens` int DEFAULT NULL COMMENT '输出token数',
  `total_tokens` int DEFAULT NULL COMMENT '总token数',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标识：0未删除，1已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_call_id` (`call_id`),
  KEY `idx_trace_id` (`trace_id`),
  KEY `idx_scene_biz` (`scene`, `biz_id`),
  KEY `idx_provider_model_time` (`provider`, `model_id`, `create_time`),
  KEY `idx_status_time` (`status`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='大模型调用日志表';
