CREATE TABLE IF NOT EXISTS rag_resume_document (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    resume_id VARCHAR(64) NOT NULL COMMENT '简历业务唯一标识',
    file_id VARCHAR(64) NOT NULL COMMENT '关联文件file_id',
    candidate_name VARCHAR(128) DEFAULT NULL COMMENT '候选人姓名',
    source_type VARCHAR(32) NOT NULL DEFAULT 'RESUME' COMMENT '来源类型',
    parse_status VARCHAR(32) NOT NULL DEFAULT 'INIT' COMMENT '解析状态 INIT/PARSED/CHUNKED/EMBEDDED/FAILED',
    mime_type VARCHAR(128) DEFAULT NULL COMMENT '文档MIME类型',
    original_text MEDIUMTEXT COMMENT 'Tika提取后的原始文本',
    cleaned_text MEDIUMTEXT COMMENT '清洗后的文本',
    section_count INT NOT NULL DEFAULT 0 COMMENT '识别出的section数量',
    entry_count INT NOT NULL DEFAULT 0 COMMENT '识别出的entry数量',
    chunk_count INT NOT NULL DEFAULT 0 COMMENT '最终chunk数量',
    parse_metadata JSON DEFAULT NULL COMMENT '解析元数据快照',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    del_flag TINYINT NOT NULL DEFAULT 0 COMMENT '删除标识 0-未删除 1-已删除',
    UNIQUE KEY uk_resume_id (resume_id),
    UNIQUE KEY uk_file_id (file_id),
    KEY idx_candidate_name (candidate_name),
    KEY idx_parse_status (parse_status),
    KEY idx_create_time (create_time),
    KEY idx_del_flag (del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='RAG简历文档表';


CREATE TABLE IF NOT EXISTS rag_resume_entry (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    entry_id VARCHAR(64) NOT NULL COMMENT '条目业务唯一标识',
    resume_id VARCHAR(64) NOT NULL COMMENT '关联简历resume_id',
    section_name VARCHAR(64) NOT NULL COMMENT '一级标题，如教育背景/实习经验/项目经历/技能',
    entry_type VARCHAR(32) NOT NULL COMMENT '条目类型 EDUCATION/INTERNSHIP/PROJECT/SKILL/SUMMARY',
    entry_title VARCHAR(255) DEFAULT NULL COMMENT '条目标题，如项目名/公司名/学校名',
    org_name VARCHAR(255) DEFAULT NULL COMMENT '公司或学校名称',
    role_name VARCHAR(128) DEFAULT NULL COMMENT '岗位/身份',
    time_range VARCHAR(64) DEFAULT NULL COMMENT '时间范围原文',
    start_time VARCHAR(32) DEFAULT NULL COMMENT '开始时间，保留原始格式',
    end_time VARCHAR(32) DEFAULT NULL COMMENT '结束时间，保留原始格式',
    tech_stack JSON DEFAULT NULL COMMENT '技术栈数组',
    content_text MEDIUMTEXT COMMENT '条目完整文本',
    sort_no INT NOT NULL DEFAULT 0 COMMENT '在简历中的顺序',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    del_flag TINYINT NOT NULL DEFAULT 0 COMMENT '删除标识 0-未删除 1-已删除',
    UNIQUE KEY uk_entry_id (entry_id),
    KEY idx_resume_id (resume_id),
    KEY idx_section_name (section_name),
    KEY idx_entry_type (entry_type),
    KEY idx_org_name (org_name),
    KEY idx_time_range (time_range),
    KEY idx_sort_no (sort_no),
    KEY idx_del_flag (del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='RAG简历结构化条目表';


CREATE TABLE IF NOT EXISTS rag_resume_chunk (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    chunk_id VARCHAR(64) NOT NULL COMMENT 'chunk业务唯一标识',
    resume_id VARCHAR(64) NOT NULL COMMENT '关联简历resume_id',
    entry_id VARCHAR(64) DEFAULT NULL COMMENT '关联条目entry_id',
    file_id VARCHAR(64) NOT NULL COMMENT '关联文件file_id',
    section_name VARCHAR(64) NOT NULL COMMENT '一级标题',
    entry_type VARCHAR(32) DEFAULT NULL COMMENT '条目类型',
    entry_title VARCHAR(255) DEFAULT NULL COMMENT '条目标题',
    org_name VARCHAR(255) DEFAULT NULL COMMENT '公司或学校名称',
    role_name VARCHAR(128) DEFAULT NULL COMMENT '岗位/身份',
    time_range VARCHAR(64) DEFAULT NULL COMMENT '时间范围',
    part_index INT NOT NULL DEFAULT 0 COMMENT '当前子块序号，从0开始',
    part_total INT NOT NULL DEFAULT 1 COMMENT '同条目总块数',
    token_count INT NOT NULL DEFAULT 0 COMMENT '估算token数',
    char_count INT NOT NULL DEFAULT 0 COMMENT '字符数',
    overlap_chars INT NOT NULL DEFAULT 0 COMMENT '与前块的重叠字符数',
    chunk_text MEDIUMTEXT NOT NULL COMMENT 'chunk文本',
    summary_text VARCHAR(500) DEFAULT NULL COMMENT 'chunk摘要，可用于召回展示',
    metadata_json JSON DEFAULT NULL COMMENT 'chunk元数据快照',
    embed_status VARCHAR(32) NOT NULL DEFAULT 'INIT' COMMENT '向量化状态 INIT/EMBEDDED/FAILED',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    del_flag TINYINT NOT NULL DEFAULT 0 COMMENT '删除标识 0-未删除 1-已删除',
    UNIQUE KEY uk_chunk_id (chunk_id),
    KEY idx_resume_id (resume_id),
    KEY idx_entry_id (entry_id),
    KEY idx_file_id (file_id),
    KEY idx_section_name (section_name),
    KEY idx_entry_type (entry_type),
    KEY idx_time_range (time_range),
    KEY idx_embed_status (embed_status),
    KEY idx_del_flag (del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='RAG简历切块表';
