CREATE TABLE IF NOT EXISTS rag_file (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    file_id VARCHAR(64) NOT NULL COMMENT '文件业务唯一标识',
    file_name VARCHAR(255) NOT NULL COMMENT '原始文件名',
    file_ext VARCHAR(32) DEFAULT NULL COMMENT '文件后缀',
    content_type VARCHAR(128) DEFAULT NULL COMMENT '文件类型',
    file_size BIGINT NOT NULL DEFAULT 0 COMMENT '文件大小(byte)',
    bucket_name VARCHAR(128) NOT NULL COMMENT '对象存储桶名',
    object_key VARCHAR(512) NOT NULL COMMENT '对象存储路径',
    object_url VARCHAR(1024) DEFAULT NULL COMMENT '文件访问地址',
    status VARCHAR(32) NOT NULL DEFAULT 'UPLOADED' COMMENT '文件状态',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    del_flag TINYINT NOT NULL DEFAULT 0 COMMENT '删除标识 0-未删除 1-已删除',
    UNIQUE KEY uk_file_id (file_id),
    KEY idx_file_name (file_name),
    KEY idx_status (status),
    KEY idx_create_time (create_time),
    KEY idx_del_flag (del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='RAG上传文件表';
