server:
  port: 10010

spring:
  application:
    name: Job-backed
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/job_backed?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  sql:
    init:
      mode: always
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB


app:
  jwt:
    secret: jobbacked-demo-secret-key-jobbacked-demo-secret-key
    expiration-hours: 24


rustfs:
  url: http://localhost:9000
  access-key-id: rustfsadmin
  secret-access-key: rustfsadmin
  bucket-name: job-rag
  create-bucket-if-missing: true

job:
  semaphore:
    name: job:upload
    max-concurrent: 10
    max-wait-seconds: 30
    lease-seconds: 30
