server:
  port: 10020

spring:
  application:
    name: job-rag
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/job_backed?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

rustfs:
  url: http://localhost:9000
  access-key-id: rustfsadmin
  secret-access-key: rustfsadmin
  bucket-name: user-resume
  create-bucket-if-missing: true

rocketmq:
  name-server: 127.0.0.1:9876 # NameServer 地址
  producer:
    group: job-rag-service_common-message-execute_pg
    send-message-timeout: 10000 # 发送超时时间
    retry-times-when-send-failed: 1 # 同步发送重试次数
    retry-times-when-send-async-failed: 1 # 异步发送重试次数

ai:
  providers:
    ollama:
      url: http://localhost:11434
      endpoints:
        chat: /v1/chat/completions
        embedding: /v1/embeddings
    bailian:
      url: https://dashscope.aliyuncs.com
      api-key: sk-fa84b1f526424030b79985d311710146
      endpoints:
        chat: /compatible-mode/v1/chat/completions
        rerank: /api/v1/services/rerank/text-rerank/text-rerank
    siliconflow:
      url: https://api.siliconflow.cn
      api-key: sk-rjtfqcpnhpzonswkebygmaqnqvibqcndgqxqfxghizuguthf
      endpoints:
        chat: /v1/chat/completions
        embedding: /v1/embeddings

  selection:
    failure-threshold: 1
    open-duration-ms: 300000

  stream:
    message-chunk-size: 1

  http:
    connect-timeout-seconds: 5
    read-timeout-seconds: 60
    write-timeout-seconds: 30
    call-timeout-seconds: 90

  chat:
    default-model: qwen-plus
    deep-thinking-model: qwen3-max
    candidates:
      - id: qwen-plus
        provider: bailian
        model: qwen-plus-latest
        priority: 1
      - id: qwen3-max
        provider: bailian
        model: qwen3-max
        supports-thinking: true
        priority: 3
      - id: glm-4.7
        provider: siliconflow
        model: Pro/zai-org/GLM-4.7
        supports-thinking: true
        priority: 0
      - id: Qwen
        provider: siliconflow
        model: Qwen/Qwen3.6-35B-A3B
        priority: 2


    rerank:
      default-model: qwen3-rerank
      candidates:
        - id: qwen3-rerank
          provider: bailian
          model: qwen3-rerank
          priority: 1
        - id: rerank-noop
          provider: noop
          model: noop
          priority: 100
