server:
  port: 10020

spring:
  application:
    name: job-rag
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/job_backed?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

rustfs:
  url: http://localhost:9000
  access-key-id: rustfsadmin
  secret-access-key: rustfsadmin
  bucket-name: job-rag
  create-bucket-if-missing: true


rocketmq:
  name-server: 127.0.0.1:9876 # NameServer 地址
  producer:
    group: oneCoupon_merchant-admin-service_common-message-execute_pg
    send-message-timeout: 10000 # 发送超时时间
    retry-times-when-send-failed: 1 # 同步发送重试次数
    retry-times-when-send-async-failed: 1 # 异步发送重试次数

